name: 'Reset'

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'Branch to reset'
        required: true

  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to reset'
        options:
          - 'generated'
        required: true
  
jobs:
  resetting-tags:
    name: 'Resetting tags'
    secrets: inherit
    uses: './.github/workflows/reset_tags.yml'
    
  resetting-branch:
    name: 'Resetting branch'
    secrets: inherit
    uses: './.github/workflows/reset_branch.yml'
    with:
      branch: ${{ github.event.inputs.branch }}
